astra_db:
  collection_name: "chatbotflip"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 3

llm:
  provider: "google"
  model_name: "gemini-2.0-flash"